import type { Post, User, WithdrawalRequest } from "./types";

export const MOCK_CATEGORIES = [
  "Утас, таблет",
  "Үнэт эдлэл",
  "Дэвтэр, ном",
  "Түргэн хоол",
  "Хувцас гутал",
  "Бусад",
] as const;

export const MOCK_LOCATIONS = [
  "1-р байр",
  "2-р байр",
  "Номын сан",
  "Спорт заал",
  "4-р байр",
  "5-р байр",
  "7-р байр",
  "8-р байр",
  "Хууль зүйн сургууль",
  "Багш оюутан хөгжлийн төв",
] as const;

export const INITIAL_USERS: User[] = [
  {
    id: "u-admin",
    sisiId: "20b1num0001",
    phone: "99110011",
    email: "admin@num.edu.mn",
    name: "Админ Хэрэглэгч",
    isAdmin: true,
    password: "admin",
  },
  {
    id: "u-1",
    sisiId: "21b1num0123",
    phone: "88112233",
    email: "bold@num.edu.mn",
    facebook: "bold.num",
    name: "Болд Оюутан",
    password: "demo",
  },
  {
    id: "u-2",
    sisiId: "20b1num0456",
    phone: "89991122",
    email: "saraa@num.edu.mn",
    name: "Сараа Эрдэнэ",
    password: "demo",
  },
  {
    id: "u-3",
    sisiId: "22b1num0234",
    phone: "88119900",
    email: "temuulen@num.edu.mn",
    name: "Тэмүүлэн Бат",
    password: "demo",
  },
  {
    id: "u-4",
    sisiId: "24b1num3456",
    phone: "88000000",
    email: "engin@num.edu.mn",
    name: "Хэрэглэгч",
    password: "1234",
  },
];

export const INITIAL_POSTS: Post[] = [
  {
    id: "p-1",
    type: "lost",
    title: "AirPods Pro алдсан",
    description:
      "Цайвар кейстэй, номын сан 3 давхарт сүүлд харагдсан. Шагналтай.",
    category: "Утас, таблет",
    location: "Номын сан",
    date: "2026-03-20",
    imageUrl:
      "https://images.unsplash.com/photo-1606220945770-b5b6c2c55bf1?w=600&q=80",
    authorId: "u-1",
    status: "published",
    rewardAmount: 50000,
    verificationQuestion: "AirPods-ийн device нэр нь юу вэ?",
    correctAnswer: "Boldiin AirPods",
  },
  {
    id: "p-2",
    type: "found",
    title: "Түрийвч олдсон",
    description:
      "2-р байрын орцонд хар торгоны түрийвч. Баталгаажуулалт шаардлагатай.  ",
    category: "Үнэт эдлэл",
    location: "2-р байр",
    date: "2026-03-22",
    imageUrl:
      "https://images.unsplash.com/photo-1627123424574-724758594e93?w=600&q=80",
    authorId: "u-admin",
    status: "published",
    verificationQuestion: "Дотор нь хэдэн карт байсан бэ?",
    correctAnswer: "2",
    finderRewardAmount: 30000,
  },
  {
    id: "p-3",
    type: "lost",
    title: "Физикийн ном (IV том)",
    description: "Ногоон хавтас, гарын үсэгтэй.",
    category: "Дэвтэр, ном",
    location: "1-р байр",
    date: "2026-03-18",
    imageUrl:
      "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=600&q=80",
    authorId: "u-1",
    status: "published",
    verificationQuestion: "Номын эхний хуудсан дээрх нэрийн эхний үсэг юу вэ?",
    correctAnswer: "Б",
  },
  {
    id: "p-4",
    type: "found",
    title: "Түлхүүр олдсон",
    description: "NUM лого бүхий түлхүүр.",
    category: "Бусад",
    location: "2-р байр",
    date: "2026-03-24",
    imageUrl:
      "https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=600&q=80",
    authorId: "u-1",
    status: "published",
    verificationQuestion: "Түлхүүрийн оосор ямар өнгөтэй вэ?",
    correctAnswer: "хар",
  },
  {
    id: "p-5",
    type: "lost",
    title: "Samsung Galaxy утас",
    description: "Хар гэртэй, баруун доод буланд нь хагаралтай.",
    category: "Утас, таблет",
    location: "Спорт заал",
    date: "2026-03-15",
    imageUrl:
      "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=600&q=80",
    authorId: "u-2",
    status: "published",
    rewardAmount: 80000,
    verificationQuestion: "Утасны дэлгэцийн хагарал аль буланд байсан бэ?",
    correctAnswer: "баруун доод",
  },
  {
    id: "p-6",
    type: "found",
    title: "Хар шүхэр",
    description: "Номын сангаас гарах үед суудал дээр үлдсэн.",
    category: "Бусад",
    location: "Номын сан",
    date: "2026-03-21",
    imageUrl:
      "https://images.unsplash.com/photo-1523772721666-22ad3c3b6f90?w=600&q=80",
    authorId: "u-3",
    status: "published",
    verificationQuestion: "Хэдэн эгнээтэй вэ?",
    correctAnswer: "8",
  },
  {
    id: "p-7",
    type: "lost",
    title: "Ухаалаг цаг Apple Watch",
    description: "Цайвар спорт ремэнтэй, цэнэг бага байсан.",
    category: "Утас, таблет",
    location: "Номын сан",
    date: "2026-03-19",
    imageUrl:
      "https://images.unsplash.com/photo-1434493789847-2f02dc6ca35d?w=600&q=80",
    authorId: "u-2",
    status: "published",
    verificationQuestion: "Apple Watch-ийн ремэн ямар өнгөтэй вэ?",
    correctAnswer: "цайвар",
  },
  {
    id: "p-8",
    type: "found",
    title: "Математикийн дэвтэр",
    description: "Цэнхэр хавтас, эхний хуудсанд Б.Бат гэж бичсэн.",
    category: "Дэвтэр, ном",
    location: "1-р байр",
    date: "2026-03-23",
    imageUrl:
      "https://images.unsplash.com/photo-1456513080510-7bf3a96b5d59?w=600&q=80",
    authorId: "u-1",
    status: "published",
    verificationQuestion: "Хавтас ямар өнгөтэй вэ?",
    correctAnswer: "цэнхэр",
    finderRewardAmount: 10000,
  },
  {
    id: "p-9",
    type: "lost",
    title: "Лабораторийн шилэн сав",
    description: "Химийн хичээлийн 250мл хэмжээстэй.",
    category: "Бусад",
    location: "Номын сан",
    date: "2026-03-17",
    imageUrl:
      "https://images.unsplash.com/photo-1532187863486-abf9dbad1b69?w=600&q=80",
    authorId: "u-3",
    status: "published",
    verificationQuestion: "Шилэн савны хэмжээ хэдэн мл вэ?",
    correctAnswer: "250",
  },
  {
    id: "p-10",
    type: "found",
    title: "USB-C цэнэглэгч",
    description: "Цагаан адаптер, урт кабельтай.",
    category: "Утас, таблет",
    location: "8-р байр",
    date: "2026-03-25",
    imageUrl:
      "https://images.unsplash.com/photo-1583863788434-e42a44cbd7aa?w=600&q=80",
    authorId: "u-admin",
    status: "published",
    verificationQuestion: "Кабель ямар өнгөтэй вэ?",
    correctAnswer: "цагаан",
  },
  {
    id: "p-11",
    type: "lost",
    title: "Спортын цүнх Nike",
    description: "Хар, хажууд нь цагаан зураас.",
    category: "Бусад",
    location: "Спорт заал",
    date: "2026-03-14",
    imageUrl:
      "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600&q=80",
    authorId: "u-1",
    status: "published",
    rewardAmount: 40000,
    verificationQuestion: "Цүнхний брэнд юу вэ?",
    correctAnswer: "Nike",
  },
  {
    id: "p-12",
    type: "found",
    title: "Нүдний шил",
    description: "Хүрэн жижиг савтай, хайрцаг дотор.",
    category: "Үнэт эдлэл",
    location: "Номын сан",
    date: "2026-03-16",
    imageUrl:
      "https://images.unsplash.com/photo-1574258495973-f010dfbb5371?w=600&q=80",
    authorId: "u-2",
    status: "published",
    verificationQuestion: "Сав ямар өнгөтэй вэ?",
    correctAnswer: "хүрэн",
  },
  {
    id: "p-13",
    type: "lost",
    title: "Кредит картны түрийвч",
    description: "Бор арьсан, дотор нь оюутны үнэмлэх.",
    category: "Үнэт эдлэл",
    location: "4-р байр",
    date: "2026-03-13",
    imageUrl:
      "https://images.unsplash.com/photo-1620591549194-f5a4c4d07f6f?w=600&q=80",
    authorId: "u-3",
    status: "published",
    verificationQuestion: "Түрийвч ямар материалтай вэ?",
    correctAnswer: "арьсан",
  },
  {
    id: "p-14",
    type: "found",
    title: "Цайны халбага, сэрээ",
    description: "Халуун тогооны өрөөнд цагаан савтай.",
    category: "Түргэн хоол",
    location: "1-р байр",
    date: "2026-03-26",
    imageUrl:
      "https://images.unsplash.com/photo-1556910096-6f5e72db6803?w=600&q=80",
    authorId: "u-1",
    status: "published",
    verificationQuestion: "Сав ямар материалтай вэ?",
    correctAnswer: "хуванцар",
  },
  {
    id: "p-15",
    type: "lost",
    title: "iPad mini",
    description: "Хар кейстэй, ард талд наалттай.",
    category: "Утас, таблет",
    location: "Номын сан",
    date: "2026-03-12",
    imageUrl:
      "https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=600&q=80",
    authorId: "u-2",
    status: "published",
    rewardAmount: 120000,
    verificationQuestion: "iPad-ийн кейс ямар өнгөтэй вэ?",
    correctAnswer: "хар",
  },
  {
    id: "p-16",
    type: "found",
    title: "Малгай (beanie)",
    description: "Саарал өнгөтэй, номын сан 2 давхарт.",
    category: "Хувцас гутал",
    location: "Номын сан",
    date: "2026-03-11",
    imageUrl:
      "https://images.unsplash.com/photo-1576871337622-fd40de0124f6?w=600&q=80",
    authorId: "u-3",
    status: "published",
    verificationQuestion: "Ямар өнгөтэй вэ?",
    correctAnswer: "саарал",
  },
  {
    id: "p-17",
    type: "lost",
    title: "Хими ном (орчуулсан хувилбар)",
    description: "Улаан хавтас, 2024 хэвлэл.",
    category: "Дэвтэр, ном",
    location: "2-р байр",
    date: "2026-03-10",
    imageUrl:
      "https://images.unsplash.com/photo-1497633762265-9d179a990aa6?w=600&q=80",
    authorId: "u-admin",
    status: "published",
    verificationQuestion: "Номын хавтас ямар өнгөтэй вэ?",
    correctAnswer: "улаан",
  },
  {
    id: "p-18",
    type: "found",
    title: "Bluetooth чихэвч",
    description: "Хар, жижиг цэнэглэх хайрцагтай.",
    category: "Утас, таблет",
    location: "Спорт заал",
    date: "2026-03-09",
    imageUrl:
      "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&q=80",
    authorId: "u-2",
    status: "published",
    verificationQuestion: "Өнгө нь?",
    correctAnswer: "хар",
    finderRewardAmount: 15000,
  },
  {
    id: "p-19",
    type: "lost",
    title: "Оюутны үнэмлэх",
    description: "Хамт цүнхтэй алдсан, цэнхэр оосортой.",
    category: "Бусад",
    location: "1-р байр",
    date: "2026-03-08",
    imageUrl:
      "https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=600&q=80",
    authorId: "u-3",
    status: "published",
    rewardAmount: 200000,
    verificationQuestion: "Оюутны үнэмлэхний оосор ямар өнгөтэй вэ?",
    correctAnswer: "цэнхэр",
  },
  {
    id: "p-20",
    type: "found",
    title: "Усны сав (1.5л)",
    description: "Цэнхэр тагтай, спорт заалны орцонд.",
    category: "Түргэн хоол",
    location: "Спорт заал",
    date: "2026-03-07",
    imageUrl:
      "https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=600&q=80",
    authorId: "u-1",
    status: "published",
    verificationQuestion: "Таг ямар өнгөтэй вэ?",
    correctAnswer: "цэнхэр",
  },
  {
    id: "p-21",
    type: "lost",
    title: "HP зөөврийн компьютерын хулгана",
    description: "Хар wireless mouse, 5-р байранд семинарын дараа үлдээсэн байж магадгүй.",
    category: "Утас, таблет",
    location: "5-р байр",
    date: "2026-04-01",
    imageUrl: "https://images.unsplash.com/photo-1527814050087-3793815479db?w=600&q=80",
    authorId: "u-2",
    status: "published",
    rewardAmount: 15000,
    verificationQuestion: "Хулганын брэнд юу вэ?",
    correctAnswer: "HP",
  },
  {
    id: "p-22",
    type: "found",
    title: "Алтан өнгийн бөгж олдсон",
    description: "7-р байрны коридороос олдсон, дотор талдаа жижиг бичиглэлтэй.",
    category: "Үнэт эдлэл",
    location: "7-р байр",
    date: "2026-04-02",
    imageUrl: "https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=600&q=80",
    authorId: "u-1",
    status: "published",
    verificationQuestion: "Бөгжний дотор талд юу сийлсэн бэ?",
    correctAnswer: "A",
    finderRewardAmount: 25000,
  },
  {
    id: "p-23",
    type: "lost",
    title: "Микро эдийн засгийн гарын авлага",
    description: "Нил ягаан хавтастай, дотор нь шар sticky note-уудтай.",
    category: "Дэвтэр, ном",
    location: "4-р байр",
    date: "2026-04-02",
    imageUrl: "https://images.unsplash.com/photo-1512820790803-83ca734da794?w=600&q=80",
    authorId: "u-3",
    status: "published",
    verificationQuestion: "Номын хавтас ямар өнгөтэй вэ?",
    correctAnswer: "нил ягаан",
  },
  {
    id: "p-24",
    type: "found",
    title: "Burger box олдсон",
    description: "Багш оюутан хөгжлийн төвийн ширээн дээр эзэнгүй үлдсэн.",
    category: "Түргэн хоол",
    location: "Багш оюутан хөгжлийн төв",
    date: "2026-04-03",
    imageUrl: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=600&q=80",
    authorId: "u-admin",
    status: "published",
    verificationQuestion: "Дотор нь ямар төрлийн бургер байсан бэ?",
    correctAnswer: "үхрийн махтай",
  },
  {
    id: "p-25",
    type: "lost",
    title: "Цэнхэр жийнсэн хүрэм",
    description: "Номын сангийн өлгүүр дээр орхиод явсан байж магадгүй.",
    category: "Хувцас гутал",
    location: "Номын сан",
    date: "2026-04-03",
    imageUrl: "https://images.unsplash.com/photo-1541099649105-f69ad21f3246?w=600&q=80",
    authorId: "u-4",
    status: "published",
    rewardAmount: 30000,
    verificationQuestion: "Хүрэмний товч ямар өнгөтэй вэ?",
    correctAnswer: "мөнгө",
  },
  {
    id: "p-26",
    type: "found",
    title: "Canon calculator",
    description: "Хууль зүйн сургуулийн лекцийн танхимд ширээн дээр үлдсэн байсан.",
    category: "Бусад",
    location: "Хууль зүйн сургууль",
    date: "2026-04-04",
    imageUrl: "https://images.unsplash.com/photo-1567427018141-0584cfcbf1b8?w=600&q=80",
    authorId: "u-2",
    status: "published",
    verificationQuestion: "Тооны машины өнгө ямар вэ?",
    correctAnswer: "саарал",
  },
  {
    id: "p-27",
    type: "lost",
    title: "Anker power bank",
    description: "Хар өнгөтэй, 10000mAh багтаамжтай, 8-р байранд алдсан.",
    category: "Утас, таблет",
    location: "8-р байр",
    date: "2026-04-05",
    imageUrl: "https://images.unsplash.com/photo-1609091839311-d5365f9ff1c5?w=600&q=80",
    authorId: "u-1",
    status: "published",
    rewardAmount: 35000,
    verificationQuestion: "Power bank-ийн багтаамж хэд вэ?",
    correctAnswer: "10000",
  },
  {
    id: "p-28",
    type: "found",
    title: "Сувдан зүүлт",
    description: "1-р байрны шатан дээрээс олдсон, жижиг уутанд хийж хадгалсан.",
    category: "Үнэт эдлэл",
    location: "1-р байр",
    date: "2026-04-05",
    imageUrl: "https://images.unsplash.com/photo-1611652022419-a9419f74343d?w=600&q=80",
    authorId: "u-3",
    status: "published",
    verificationQuestion: "Зүүлт хэдэн сувдтай вэ?",
    correctAnswer: "5",
    finderRewardAmount: 20000,
  },
  {
    id: "p-29",
    type: "lost",
    title: "Organic chemistry notebook",
    description: "Англи хэл дээр тэмдэглэлтэй, бор хавтастай дэвтэр.",
    category: "Дэвтэр, ном",
    location: "2-р байр",
    date: "2026-04-06",
    imageUrl: "https://images.unsplash.com/photo-1455390582262-044cdead277a?w=600&q=80",
    authorId: "u-2",
    status: "published",
    verificationQuestion: "Дэвтэр дээр ямар хичээлийн нэр байсан бэ?",
    correctAnswer: "organic chemistry",
  },
  {
    id: "p-30",
    type: "found",
    title: "Хар Adidas малгай",
    description: "Спорт заалны суудлын доороос олдсон, урд талдаа цагаан логотой.",
    category: "Хувцас гутал",
    location: "Спорт заал",
    date: "2026-04-07",
    imageUrl: "https://images.unsplash.com/photo-1521369909029-2afed882baee?w=600&q=80",
    authorId: "u-admin",
    status: "published",
    verificationQuestion: "Малгайн логo ямар өнгөтэй вэ?",
    correctAnswer: "цагаан",
  }
];

export const INITIAL_WITHDRAWALS: WithdrawalRequest[] = [];
